@startuml
hide empty description

state リスクマネジメントプロセスのはじめの一歩 {
  はじめの一歩 --> リスク評価
  リスク評価 --> リソースの棚卸し
  リソースの棚卸し --> リスク優先順位づけ
  リスク優先順位づけ --> リスク管理と意思決定
}

リスク評価 : - SLO に定義すべき可用性とレイテンシをどう定めるか？
リスク評価 : - ダウンタイム発生時、サービスに与える影響は？
リスク評価 : - サービスがダウンしている間の損害は何か？

リソースの棚卸し : - データセンター
リソースの棚卸し : - ソフトウェア群
リソースの棚卸し : - ソフトウェア群におけるロール
リソースの棚卸し : - ソフトウェア群における相互通信
リソースの棚卸し : - ソフトウェア群におけるジョブ

リスク優先順位づけ : SLO に定義した各指標を潜在的に侵す可能性がある各リスクについて
リスク優先順位づけ : - そのリスクが現実となって起こりうる可能性
リスク優先順位づけ : - 発生した場合にもたらす影響
リスク優先順位づけ : のそれぞれを考慮して優先順位を決定する。

@enduml
