@startuml
hide empty description

state リスク管理プロセスにおける継続的改善作業 {
  はじめの一歩 -down-> サービスのリスク評価
  サービスデリバリの評価 #88f -left-> サービスのリスク評価
  サービスのリスク評価 -down-> リソースの棚卸し
  リソースの棚卸し -down-> リスク優先順位づけ
  リスク優先順位づけ -down-> リスク管理と意思決定
  インシデント管理 #88f -left-> リスク優先順位づけ: ポストモーテム

  リスク管理と意思決定 -up-> リスク優先順位づけ

  リスク管理と意思決定 -right-> アーキテクチャのパイプライン
  アーキテクチャのパイプライン #88f -up-> リソースの棚卸し: 新しいコンポーネント

}
skinparam node {
borderColor Green
backgroundColor Yellow
backgroundColor<<shared node>> Magenta
}
@enduml